[package]
name = "yes-rs"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
opt-level = 3

[dependencies]
rustix = { version = "1.0.7", default-features = false, features = ["pipe", "std"] }
